spring:

  # redis 配置
  redis:
    host: ${yicode.redis.host}
    port: ${yicode.redis.port}
    database: ${yicode.redis.database}
    password: ${yicode.redis.password}

  # oss
  cloud:
    alicloud:
      access-key: ${yicode.alicloud.oss.access-key}
      secret-key: ${yicode.alicloud.oss.secret-key}
      oss:
        endpoint: ${yicode.alicloud.oss.endpoint}

  #邮件发送配置
  mail:
    username: ${yicode.email.username}
    password: ${yicode.email.password}
    host: smtp.qq.com
    # 开启加密授权验证
    properties:
      mail:
        smtp:
          ssl:
            enable:
              true


# feign
feign:
  client:
    yicode-user:
      name: yicode-user


management:
  endpoints:
    web:
      exposure:
        include: "*" # 开放所有端点 默认值只打开 health 和 info 两个端点
  endpoint:
    # health 端点配置项
    health:
      enabled: true
      show-details: always # 永远展示完整信息