server:
  port: 13100

spring:
  application:
    name: yicode-auth
  profiles:
    active: dev
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 8c2ee21d-78f7-48fc-8ba3-66ce5183571f

  # redis 配置
  redis:
    port: 9942
    host: 175.24.229.41
    database: 10
    password: DLgWoryp1S0xtfC4*PVM

management:
  endpoints:
    web:
      exposure:
        include: "*" # 开放所有端点 默认值只打开 health 和 info 两个端点
  endpoint:
    # health 端点配置项
    health:
      enabled: true
      show-details: always # 永远展示完整信息