spring:
  # redis 配置
  redis:
    host: ${yicode.redis.host}
    port: ${yicode.redis.port}
    database: ${yicode.redis.database}
    password: ${yicode.redis.password}

  main:
    allow-bean-definition-overriding: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false


feign:
  client:
    yicode-thirdpart:
      name: yicode-thirdpart
    yicode-user:
      name: yicode-user
    config:
      yicode-thirdpart:
        connect-timeout: 30000
        read-timeout: 30000
      yicode-user:
        connect-timeout: 30000
        read-timeout: 30000

logging:
  level:
    com.yixihan.yicode.thirdpart.openapi.biz.feign: debug

management:
  endpoints:
    web:
      exposure:
        include: "*" # 开放所有端点 默认值只打开 health 和 info 两个端点
  endpoint:
    # health 端点配置项
    health:
      enabled: true
      show-details: always # 永远展示完整信息
